### ISSUE TITLE
Is the ESP8266 supported with this library?

### ISSUE THREAD

**Issue by rglissmann** [pikido-edutainment/CleanRTOS#1]
This library doesn't compile when an ESP8266 is selected. Is this valid?

In file included from c:\Users\Randy\Documents\Arduino 2\libraries\CleanRTOS\src/crt_CleanRTOS.h:7,
                 from C:\Users\Randy\AppData\Local\Temp\.arduinoIDE-unsaved2022101-4880-gdvrep.iqf9\HelloWorld\HelloWorld_ino.h:3,
                 from C:\Users\Randy\AppData\Local\Temp\.arduinoIDE-unsaved2022101-4880-gdvrep.iqf9\HelloWorld\HelloWorld.ino:7:
c:\Users\Randy\Documents\Arduino 2\libraries\CleanRTOS\src/internals/crt_FreeRTOS.h:4:10: fatal error: freertos/FreeRTOS.h: No such file or directory
    4 | #include "freertos/FreeRTOS.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by pikido-edutainment** [comment]
Hi Randy,

That may very well be the case. So far, this library has been developed for and tested on ESP32 only.
Having said that, it has only a few dependencies on freertos. 
I think it should be possible to port it to ESP8266 without too much effort.

Kind Regards, Marius

**Comment by rglissmann** [comment]
Thanks for your response. For many reasons I have decided to move to the
ESP32c3, so I won't be using the ESP8266 anyway.

-Randy

**Comment by pikido-edutainment** [comment]
With pleasure. Enjoy!
