### ISSUE TITLE
Using MQTT and CleanRTOS

### ISSUE THREAD

**Issue by GusanoGris** [pikido-edutainment/CleanRTOS#2]
Hello

I'm trying to get a WebServer and MQTT to work together, but I'm not able to fix it.

If I create 2 tasks, one for the WebServer and one for MQTT, it does not compile as it says that the crt::callback function cannot be converted to std::callback.

Of course, if I leave the functionality in the ino and try to use a task for the WebServer, it fails at runtime and constantly restarts.

Is there a way to make MQTT work as a task using your libraries?

The reason for this is to be able to have an MQTT configuration page and ethernet parameters via a web page.

Now I do it with MQTT messages, but I need an app with a client and (sometimes) an MQTT broker to do it and it's not very effective.

**Comment by pikido-edutainment** [comment]
Hello Gusano,

Recently, some of my students have been using CleanRTOS together with MQTT, without problems.
It sounds like you'll have to be more precise with using namespaces. Note: everything that you declare within a
crt namespace clause (like a function called callback) implicitly becomes prefixed with crt::
If you don't want that, it's better to leave out the crt namespace clause, and prefix all crt related manually
within that file. Like crt::Task, crt::Queue, etc.
If you'd like me to take a look, please post the relevant code and the exact error message.

Kind Regards, Marius

**Comment by GusanoGris** [comment]
I have solved the issue by leaving MQTT in the ino and creating a task for the WebServer.

It's not a very elegant way to do it, but I couldn't keep getting stuck on that problem.

Part of the thing is that I haven't used c++ in years.

Thank you for answering my inquiry.

**Comment by pikido-edutainment** [comment]
With pleasure, I'm glad you have been able to get your code working.

Kind Regards, Marius


Op di 3 jan. 2023 om 09:40 schreef GusanoGris ***@***.***>:
